package com.ilya.idea.utils;

public class testSortedList {
    public static void main(String[] args) {
        SortedList<String> testSortedList = new SortedList<>();
        System.out.println("---------------------------work with empty SortedList-----------------------------------------");
        System.out.println(testSortedList.size());
        System.out.println(testSortedList.isEmpty());
        System.out.println(testSortedList.get(9));
        System.out.println(testSortedList.get(1));
        System.out.println(testSortedList);
        System.out.println("--------------------------------------------------------------------");
        testSortedList.add("Ilya");
        System.out.println(testSortedList);
        System.out.println("--------------------------------------------------------------------");
        System.out.println(testSortedList.size());
        System.out.println(testSortedList.remove(-200));
        System.out.println(testSortedList);
        System.out.println(testSortedList.remove(100));
        System.out.println(testSortedList);
        System.out.println(testSortedList.indexOf("Ilya"));
        System.out.println("--------------------------------------------------------------------");
        testSortedList.add("Anna");
        testSortedList.add("Anna1");
        testSortedList.add("Denis");
        testSortedList.add("Klim");
        testSortedList.add("Maria");
        testSortedList.add("Andrew");
        System.out.println(testSortedList);
        System.out.println(testSortedList.indexOf("Anna"));
        System.out.println(testSortedList.indexOf("Klim"));
        System.out.println(testSortedList.indexOf("Maria"));
        System.out.println(testSortedList.indexOf("Vasya"));
        System.out.println("--------------------------------------------------------------------");
        testSortedList.add("Anna2");
        testSortedList.add("Denis1");
        testSortedList.add("Klim1");
        testSortedList.add("Maria1");
        testSortedList.add("Andrew1");
        testSortedList.add("1");
        testSortedList.add("10");
        testSortedList.add("20");
        testSortedList.add("90");
        testSortedList.add("100");
        testSortedList.add("25");
        testSortedList.add("15");
        testSortedList.add("9");
        testSortedList.add("29");
        System.out.println(testSortedList);
        System.out.println("--------------------------------------------------------------------");
        System.out.println(testSortedList.contains("Andrew"));
        System.out.println(testSortedList.contains("Maria"));
        System.out.println(testSortedList.contains("1"));
        System.out.println(testSortedList.contains("100"));
        System.out.println(testSortedList.contains("90"));
        System.out.println(testSortedList.contains("Dmitriy"));
        System.out.println(testSortedList.contains("Svetlana"));
        System.out.println(testSortedList.contains("Klim"));
        System.out.println("--------------------------------------------------------------------");
        System.out.println(testSortedList.get(testSortedList.size()));
        System.out.println(testSortedList.get(testSortedList.size() - 1));
        System.out.println(testSortedList.get(0));
        System.out.println(testSortedList.get(-1));
        System.out.println(testSortedList.get(5));
        System.out.println("--------------------------------------------------------------------");
        System.out.println(testSortedList);
        SortedList<String> testSortedList1 = new SortedList<>(testSortedList);
        System.out.println(testSortedList1);
        System.out.println(testSortedList.size());
        System.out.println(testSortedList.remove(15));
        System.out.println(testSortedList.remove(13));
        System.out.println(testSortedList.remove(3));
        System.out.println(testSortedList);
        System.out.println(testSortedList1.remove(12));
        System.out.println(testSortedList1.remove(16));
        System.out.println(testSortedList1.remove(15));
        System.out.println(testSortedList1);
        System.out.println(testSortedList);
    }
}
